version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore .\Natery.MultiPhaseProcessor\Natery.MultiPhaseProcessor.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: aMlVPqeUWSuEWMt6RFwIYEWYGc3EvUKPHIB9f2LbvXTmow0oTKdgHbui2rxBMibA
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false